services:
    - docker

stages:
  - test
  - name: deploy
    if: (branch = main) AND (NOT (type = pull_request))

jobs:
  include:
    - stage: test
      script:
        - docker build --target test --tag todo-app:test .
        - docker run todo-app:test test
        - docker run -e TRELLO_API_KEY -e TRELLO_API_SECRET todo-app:test e2e_test
    - stage: deploy
      script:
        - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
        - docker build --target prod --tag "${DOCKER_USERNAME}/todo-app:latest" --tag "${DOCKER_USERNAME}/todo-app:${TRAVIS_COMMIT}" .
        - docker push "${DOCKER_USERNAME}/todo-app" --all-tags
        - echo "$HEROKU_API_KEY" | docker login --username=_ --password-stdin registry.heroku.com
        - docker tag "${DOCKER_USERNAME}/todo-app:latest" registry.heroku.com/aptem-todo-app-sh/web
        - docker push registry.heroku.com/aptem-todo-app-sh/web
        - heroku container:release web 
