services:
    - docker

script:
    - docker build --target test --tag todo-app:test .
    - docker run todo-app:test test
    - docker run -e TRELLO_API_KEY -e TRELLO_API_SECRET todo-app:test e2e_test
